server:
  port: 9193
#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    driverClassName: org.h2.Driver
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console.enabled: true

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_SCHEMA:PLADB}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    dialect: POSTGRES
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          #auto: create
          auto: update
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect